<#
.SYNOPSIS
  Budget Tracker installer for Windows (Docker Desktop + WSL2).
.DESCRIPTION
  Idempotent. Never overwrites an existing SECRET_KEY. Mirrors install/install-linux.sh.
#>
[CmdletBinding()]
param(
  [switch]$Update,
  [switch]$Uninstall,
  [switch]$PurgeData,
  [string]$Load = '',
  [int]$Port = 3000,
  [switch]$DryRun,
  [switch]$Help
)

$ErrorActionPreference = 'Stop'

$Service = 'budget-tracker'
$Image = 'budget-tracker:latest'
$ProjectDir = Split-Path -Parent $PSScriptRoot
$OverrideFile = Join-Path $ProjectDir 'docker-compose.override.yml'

function Show-Usage {
  @'
Budget Tracker installer (Windows)

Usage: .\install\install-windows.ps1 [options]

  -Update            Rebuild the image and restart. Your data is preserved.
  -Uninstall         Stop and remove the container and image. Data is kept.
  -PurgeData         With -Uninstall, also delete .\data. IRREVERSIBLE.
  -Load <image.tar>  docker load a prebuilt image instead of building.
  -Port <n>          Serve on this host port instead of 3000.
  -DryRun            Print every action without doing any of them.
  -Help              Show this message.
'@ | Write-Output
}

function Write-Step { param([string]$Message) Write-Output "`n==> $Message" }
function Write-Info { param([string]$Message) Write-Output $Message }
function Write-Warn { param([string]$Message) Write-Warning $Message }

function Invoke-Step {
  param([string]$Command, [string[]]$Arguments)
  if ($DryRun) {
    Write-Info "[dry-run] would run: $Command $($Arguments -join ' ')"
    return
  }
  & $Command @Arguments
  if ($LASTEXITCODE -ne 0) { throw "$Command exited with $LASTEXITCODE" }
}

function Test-Prerequisites {
  Write-Step 'Checking prerequisites'
  $ok = $true

  if (Get-Command docker -ErrorAction SilentlyContinue) {
    Write-Info "docker: $(docker --version)"
  }
  else {
    $ok = $false
    Write-Warn 'Docker Desktop is not installed or not on PATH.'
    Write-Info '  Install it from https://www.docker.com/products/docker-desktop/'
    Write-Info '  or run:  winget install -e --id Docker.DockerDesktop'
  }

  # Docker Desktop on Windows needs the WSL2 backend.
  $wsl = Get-Command wsl -ErrorAction SilentlyContinue
  if ($wsl) {
    $status = (& wsl --status) 2>&1 | Out-String
    Write-Info 'WSL is installed.'
    if ($status -notmatch '2') {
      Write-Warn 'WSL2 does not look like the default version. Run:  wsl --set-default-version 2'
    }
  }
  else {
    $ok = $false
    Write-Warn 'WSL2 is missing. Docker Desktop needs it. In an elevated PowerShell run:'
    Write-Info '  wsl --install'
    Write-Info '  (reboot, then start Docker Desktop once before rerunning this script)'
  }

  try {
    Invoke-Step 'docker' @('compose', 'version')
  }
  catch {
    $ok = $false
    Write-Warn 'The Docker Compose plugin is unavailable. Update Docker Desktop.'
  }

  if (-not (Test-Path (Join-Path $ProjectDir 'docker-compose.yml'))) {
    $ok = $false
    Write-Warn "docker-compose.yml was not found in $ProjectDir. Run this from inside the project folder."
  }

  if (-not $ok) {
    if ($DryRun) { Write-Warn 'Continuing anyway because this is a dry run.' }
    else { throw 'Fix the problems above and run this script again.' }
  }
}

function New-SecretKey {
  if ($DryRun) { return '<generated at install time>' }
  $bytes = New-Object 'System.Byte[]' 48
  [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
  return [System.Convert]::ToBase64String($bytes)
}

function Set-EnvFile {
  Write-Step 'Configuring'
  $envFile = Join-Path $ProjectDir '.env'
  if ((Test-Path $envFile) -and ((Get-Content $envFile -Raw) -match '(?m)^SECRET_KEY=.+$')) {
    Write-Info "$envFile already has a SECRET_KEY - leaving it untouched."
    return
  }
  Write-Info 'Generating a SECRET_KEY (48 random bytes).'
  Write-Info 'Keep the .env file. Losing SECRET_KEY forces every MFA user to re-enroll.'
  if ($DryRun) {
    Write-Info "[dry-run] would write: $envFile"
    return
  }
  $tz = (Get-TimeZone).Id
  @"
# Budget Tracker configuration. Generated by install-windows.ps1.
SECRET_KEY=$(New-SecretKey)
TRUST_PROXY=0
TZ=America/Toronto
# Windows time zone detected as: $tz
"@ | Set-Content -Path $envFile -Encoding UTF8
  Write-Info "wrote $envFile"
}

function Set-PortOverride {
  if ($Port -eq 3000) {
    if (Test-Path $OverrideFile) {
      Write-Step 'No -Port given; removing the port override left by an earlier run'
      if ($DryRun) { Write-Info "[dry-run] would remove: $OverrideFile" }
      else { Remove-Item -Force $OverrideFile }
    }
    return
  }
  Write-Step "Mapping the app to host port $Port"
  if ($DryRun) {
    Write-Info "[dry-run] would write: docker-compose.override.yml"
    return
  }
  @"
services:
  ${Service}:
    ports:
      - "${Port}:3000"
"@ | Set-Content -Path $OverrideFile -Encoding UTF8
  Write-Info "wrote $OverrideFile"
}

# Single source of truth for "what port is the app actually reachable on right
# now" -- reads the override file instead of trusting $Port, so a stale (or
# just-removed) override can never desync the banner/health-check from what
# docker compose will actually publish.
function Get-EffectivePort {
  if (Test-Path $OverrideFile) {
    $match = Select-String -Path $OverrideFile -Pattern '"(\d+):3000"' | Select-Object -First 1
    if ($match -and $match.Matches[0].Groups[1].Value) {
      return [int]$match.Matches[0].Groups[1].Value
    }
  }
  return $Port
}

function Wait-Healthy {
  param([int]$EffectivePort)
  Write-Step 'Waiting for the app to report healthy on /api/health'
  $url = "http://127.0.0.1:$EffectivePort/api/health"
  if ($DryRun) {
    Write-Info "[dry-run] would poll $url"
    return $true
  }
  for ($waited = 0; $waited -lt 120; $waited += 3) {
    try {
      $response = Invoke-WebRequest -Uri $url -UseBasicParsing -TimeoutSec 5
      if ($response.StatusCode -eq 200) {
        Write-Info "Healthy after ${waited}s."
        return $true
      }
    }
    catch { Start-Sleep -Seconds 3 }
  }
  Write-Warn 'The app did not become healthy within 120 seconds.'
  Write-Info "Check the logs with: docker compose logs $Service"
  return $false
}

function Show-FailureBanner {
  param([int]$EffectivePort)
  @"

============================================================
 Budget Tracker did NOT report healthy within the timeout.

 The container is left RUNNING on purpose, so you can investigate:
   docker compose logs --tail 100 $Service
   docker compose ps
   curl -v http://127.0.0.1:$EffectivePort/api/health

 Common causes: a missing or too-short SECRET_KEY, an unwritable .\data, or an
 image built for the wrong CPU architecture. See INSTALL.md's troubleshooting FAQ.
============================================================
"@ | Write-Output
}

if ($Help) { Show-Usage; exit 0 }
Set-Location $ProjectDir
if ($DryRun) { Write-Output '*** DRY RUN - nothing will be changed. ***' }

if ($Uninstall) {
  Write-Step 'Removing the container'
  Write-Info 'Running: docker compose down'
  Invoke-Step 'docker' @('compose', 'down')
  try { Invoke-Step 'docker' @('image', 'rm', $Image) } catch { Write-Warn "Image $Image was not present." }
  if ($PurgeData) {
    Write-Step 'Deleting .\data as requested by -PurgeData'
    $dataPath = Join-Path $ProjectDir 'data'
    if ($DryRun) {
      Write-Info '[dry-run] would delete .\data'
    }
    elseif (-not (Test-Path $dataPath)) {
      Write-Info 'There was no .\data directory to delete.'
    }
    else {
      Remove-Item -Recurse -Force $dataPath -ErrorAction SilentlyContinue
      if (Test-Path $dataPath) {
        Write-Warn 'Could not fully delete .\data (in use or permission denied). Remove it manually.'
      }
      else {
        Write-Info 'Data deleted.'
      }
    }
  }
  else {
    Write-Info 'Your data was kept in .\data - rerun with -PurgeData to delete it.'
  }
  exit 0
}

Test-Prerequisites

if (-not $Update) {
  Set-EnvFile
  Set-PortOverride
  Write-Step 'Preparing .\data'
  if ($DryRun) { Write-Info '[dry-run] would create .\data' }
  else { New-Item -ItemType Directory -Force (Join-Path $ProjectDir 'data') | Out-Null }
}
else {
  Write-Step 'Updating in place - your data is preserved and never touched'
}

if ($Load -ne '') {
  Write-Step "Loading the prebuilt image from $Load"
  Invoke-Step 'docker' @('load', '-i', $Load)
}
else {
  Write-Step 'Building the image (this takes a few minutes the first time)'
  Write-Info 'Running: docker compose build'
  Invoke-Step 'docker' @('compose', 'build')
}

Write-Step 'Starting the container'
Write-Info 'Running: docker compose up -d'
Invoke-Step 'docker' @('compose', 'up', '-d')

$effectivePort = Get-EffectivePort
if (Wait-Healthy -EffectivePort $effectivePort) {
  @"

============================================================
 Budget Tracker is running.

   http://localhost:$effectivePort

 First run:
   1. Open the URL above. You will land on the setup wizard.
   2. Create the first account - it becomes the administrator.
   3. Add the rest of the household under Settings -> Users.

 Useful commands (run from $ProjectDir):
   docker compose logs -f $Service
   .\install\install-windows.ps1 -Update
   .\install\install-windows.ps1 -Uninstall
============================================================
"@ | Write-Output
}
else {
  Show-FailureBanner -EffectivePort $effectivePort
  exit 1
}
