import { describe, it, expect, vi, afterEach } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import {
  TESSDATA_RELATIVE_PATH,
  TESSDATA_SHA256,
  assertOcrAssets,
  resolveOcrAssets,
} from '@/lib/warranty/ocr/assets';

describe('resolveOcrAssets (MUST-7.5)', () => {
  const assets = resolveOcrAssets();
  const entries = Object.entries(assets);

  it('returns exactly four named paths', () => {
    expect(Object.keys(assets).sort()).toEqual(['cachePath', 'corePath', 'langPath', 'workerPath']);
  });

  it.each(entries)('%s is an absolute path', (_name, value) => {
    expect(path.isAbsolute(value)).toBe(true);
  });

  it.each(entries)('%s is not a URL of any scheme', (_name, value) => {
    expect(/^[a-z]+:\/\//i.test(value)).toBe(false);
  });

  it.each(entries.filter(([name]) => name !== 'cachePath'))('%s exists on disk', (_name, value) => {
    expect(fs.existsSync(value)).toBe(true);
  });

  it('points langPath at the vendored directory, not at node_modules and not at a CDN', () => {
    expect(assets.langPath).toBe(path.join(process.cwd(), 'vendor', 'tessdata'));
    expect(fs.existsSync(path.join(assets.langPath, 'eng.traineddata.gz'))).toBe(true);
  });
});

describe('vendored language data (MUST-7.7)', () => {
  it('matches the recorded sha256 so a corrupt or swapped file fails CI', () => {
    const file = path.join(process.cwd(), TESSDATA_RELATIVE_PATH);
    const digest = createHash('sha256').update(fs.readFileSync(file)).digest('hex');
    expect(TESSDATA_SHA256).toMatch(/^[0-9a-f]{64}$/);
    expect(digest).toBe(TESSDATA_SHA256);
  });

  it('is committed, never generated by a build, a test or the app', () => {
    const script = fs.readFileSync(path.join(process.cwd(), 'scripts/fetch-tessdata.mjs'), 'utf8');
    expect(script).toMatch(/ONE-TIME/);
    const pkg = JSON.parse(fs.readFileSync(path.join(process.cwd(), 'package.json'), 'utf8')) as {
      scripts: Record<string, string>;
    };
    for (const hook of ['build', 'test', 'postinstall', 'prepare']) {
      expect(pkg.scripts[hook] ?? '').not.toContain('fetch-tessdata');
    }
  });
});

describe('assertOcrAssets', () => {
  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('reports ok with no missing entries on a healthy checkout', () => {
    expect(assertOcrAssets()).toEqual({ ok: true, missing: [] });
  });

  it('checks the core wasm builds on disk (CRITICAL 1), not just the package directory', () => {
    const assets = resolveOcrAssets();
    // tesseract.js runtime-detects SIMD support and picks between these two "-lstm" builds
    // (worker-script/node/getCore.js) — both must actually be present, since a package
    // directory existing is not proof its wasm payload is intact or wasn't stripped by an
    // overzealous prune step.
    for (const file of [
      'tesseract-core-lstm.js',
      'tesseract-core-lstm.wasm',
      'tesseract-core-simd-lstm.js',
      'tesseract-core-simd-lstm.wasm',
    ]) {
      expect(fs.existsSync(path.join(assets.corePath, file))).toBe(true);
    }
  });

  it('reports a missing entry when a core wasm file is absent, even though the package directory itself exists', () => {
    const assets = resolveOcrAssets();
    const missingWasm = path.join(assets.corePath, 'tesseract-core-simd-lstm.wasm');
    vi.spyOn(fs, 'existsSync').mockImplementation((target) => target !== missingWasm);

    const result = assertOcrAssets();
    expect(result.ok).toBe(false);
    expect(result.missing.some((entry) => entry.includes('tesseract-core-simd-lstm.wasm'))).toBe(true);
  });
});
